config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :merchants, except: :create

  namespace :api, defaults: { format: %i[json xml] } do
    namespace :v1 do
      resources :sessions, only: %i[create destroy]
      resources :transactions, only: %i[create destroy]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorize_transaction.rb
# frozen_string_literal: true

class AuthorizeTransaction < Transaction
  protected

  def skip_referenced_transaction_validation?
    true
  end
end

app/models/charge_transaction.rb
# frozen_string_literal: true

class ChargeTransaction < Transaction
  alias authorize_transaction parent

  after_save :add_to_total, if: :approved?

  protected

  def add_to_total
    merchant.update(total_transaction_sum: merchant.total_transaction_sum + amount)
  end
end

app/models/merchant.rb
# frozen_string_literal: true

class Merchant < ApplicationRecord
  enum status: %i[active inactive]

  belongs_to :user
  has_many :transactions
end

app/models/refund_transaction.rb
# frozen_string_literal: true

class RefundTransaction < Transaction
  alias charge_transaction parent

  after_save :process, if: :approved?

  protected

  def process
    update_parent_status
    remove_from_total
  end

  private

  def update_parent_status
    charge_transaction.update(status: :refunded)
  end

  def remove_from_total
    merchant.update(total_transaction_sum: merchant.total_transaction_sum + amount)
  end
end

app/models/reversal_transaction.rb
# frozen_string_literal: true

class ReversalTransaction < Transaction
  alias authorize_transaction parent

  after_save :invalidate_authorize_transaction, if: :approved?

  protected

  def skip_amount_validation?
    true
  end

  def invalidate_authorize_transaction
    authorize_transaction.update(status: :reversed)
  end
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  UUID_FORMAT = /\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\z/m.freeze

  enum status: %i[error approved reversed refunded]

  validates :uuid, presence: true, uniqueness: true, format: UUID_FORMAT
  validates :customer_email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :amount, numericality: { only_integer: true, greater_than: 0 }, unless: :skip_amount_validation?
  validate  :referenced_transaction, unless: :skip_referenced_transaction_validation?

  belongs_to :merchant
  belongs_to :parent, class_name: 'Transaction', foreign_key: 'parent_id', optional: true

  protected

  def skip_amount_validation?
    false
  end

  def skip_referenced_transaction_validation?
    false
  end

  private

  def referenced_transaction
    errors.add(:parent, :required) unless parent_id.present?
    errors.add(:parent, :invalid) unless parent.present?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  acts_as_token_authenticatable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: %i[merchant admin]

  has_one :merchant, dependent: :destroy

  def active_merchant?
    merchant&.active?
  end
end

app/controllers/api/v1/api_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ApiController < ActionController::API
      protected

      def render_json_error(error)
        if error[:type] == :activerecord
          render json: error[:value], status: :unprocessable_entity
        else
          error_object = build_error_object(error[:value])
          render json: { error: error_object }, status: error_object[:status]
        end
      end

      private

      def build_error_object(error_code)
        {}.tap do |error|
          %i[status code title].each do |field|
            error[field] = I18n.t(field, scope: "custom_errors.#{error_code}", default: nil)
          end
        end
      end
    end
  end
end

app/controllers/api/v1/authenticated_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class AuthenticatedController < ApiController
      acts_as_token_authentication_handler_for User
    end
  end
end

app/controllers/api/v1/sessions_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class SessionsController < ApiController
      def create
        user = User.find_by_email(params[:email])

        if user&.valid_password?(params[:password])
          render json: { token: user.authentication_token }, status: :created
        else
          head :unauthorized
        end
      end

      def destroy
        current_user&.authentication_token = nil
        current_user&.save ? head(:ok) : head(:unauthorized)
      end
    end
  end
end

app/controllers/api/v1/transactions_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class TransactionsController < AuthenticatedController
      before_action :authorize_user, only: :create

      def create
        result = transaction_service.create

        if result[:error].present?
          render_json_error result[:error]
        else
          render json: result[:resource]
        end
      end

      protected

      def transaction_service
        @transaction_service ||= TransactionService.new(permitted_params, current_user)
      end

      private

      def authorize_user
        head :unauthorized unless current_user.active_merchant?
      end

      def permitted_params
        params.permit(:uuid, :amount, :customer_email, :status, :parent_id, :type)
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/merchants_controller.rb
# frozen_string_literal: true

class MerchantsController < ApplicationController
  before_action :set_merchant, only: %i[show edit update destroy]

  def index
    @merchants = Merchant.all
  end

  def edit
    # TODO: Implement this action
  end

  def destroy
    @merchant.destroy
    respond_to do |format|
      format.html { redirect_to merchants_url, notice: 'Merchant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update
    respond_to do |format|
      if @merchant.update(merchant_params)
        format.html { redirect_to @merchant, notice: 'Merchant was successfully updated.' }
        format.json { render :show, status: :ok, location: @merchant }
      else
        format.html { render :edit }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_merchant
    @merchant = Merchant.find(params[:id])
  end

  def merchant_params
    params.require(:merchant).permit(:name, :description, :status)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/merchants_helper.rb
# frozen_string_literal: true

module MerchantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Emerchantpay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/merchants/_form.slim
= form_with(model: merchant, local: true) do |form|
  table
    tbody
      tr
        td
          = form.label :name
          = form.text_field :name
        td
          = form.label :description
          = form.text_area :description
        td
          = form.label :status
          = form.select(:status, Merchant.statuses.keys.map {|key| [key,key]})
  - if merchant.errors.any?
    #error_explanation
      h2
        = pluralize(merchant.errors.count, "error")
        | prohibited this merchant from being saved:
      ul
        - merchant.errors.full_messages.each do |message|
          li= message
  .actions
    = form.submit

app/views/merchants/edit.slim
h1 Editing Merchant
= render 'form', merchant: @merchant
= link_to 'Show', @merchant
| \
= link_to 'Back', merchants_path

app/views/merchants/index.slim
p#notice= notice
h1 Merchants
table
  thead
    tr
      th colspan='3'
  tbody
    th Name
    th Email
    th Status
    th colspan='2'
    - @merchants.each do |merchant|
      tr
        td= merchant.name
        td= merchant.user.email
        td= merchant.status
        td= link_to 'Show', merchant
        td= link_to 'Edit', edit_merchant_path(merchant)
        td= link_to 'Destroy', merchant, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/merchants/show.slim
p#notice= notice
= link_to 'Back', merchants_path
h1 Merchant Transactions
table
  thead
    tr
      th colspan="3" 
  tbody
    th UUID
    th Type
    th Status
    th Amount
    - @merchant.transactions.each do |transaction|
      tr
        td= transaction.uuid
        td= transaction.type
        td= transaction.status
        td= transaction.amount